### ISSUE TITLE
Uncaught error when instantiating WebAssembly

### ISSUE THREAD

**Issue by tylerchilds** [happybeing/p2p-git-portal-poc#5]
When the following line runs in `webpack:///node_modules/golang-wasm-async-loader2/dist/gobridge.js`, there is an `Uncaught (in promise) Error: undefined`.

```
WebAssembly.instantiate(bytes, go.importObject)
```

This seems to block the UI from being able to clone a repository. Uploading starts and runs, visible from the logs in the console, but never appears in the repo list. I'm assuming these are all inter-related since the above is the only error in the console.

Stack Trace:

```
Uncaught (in promise) Error: undefined gobridge.js:18
    init gobridge.js:18
    AsyncFunctionThrow self-hosted:678
    (Async: async)
    default_1 gobridge.js:20
    go main.go:2
    Webpack 9
        __webpack_require__
        svelte
        __webpack_require__
        js
        __webpack_require__
        1
        __webpack_require__
        <anonymous>
        <anonymous>
```

**Comment by happybeing** [comment]
Thanks, please can you give some more info on the steps to reproduce this and any more console output.

**Comment by tylerchilds** [comment]
@happybeing for reproducing, I'm just doing yarn dev and it happens on page load. For console output, that's all I've got :/

I put a breakpoint at the that call and tried to step in, but it errors before letting me dive into it.

**Comment by happybeing** [comment]
Just in case, can you do a clean restart by cloning from scratch as others doing this today have been able to load the app.

If it still doesn't work, let me know the browser version. Thanks.

**Comment by tylerchilds** [comment]
The above was one Firefox 82.0.2 (64-bit) Mozilla Firefox for Ubuntu.

I just tried in Brave (Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (64-bit)) too, got some extra output that looks more promising too:

```
Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #1 module="go" function="runtime.resetMemoryDataView" error: function import requires a callable
  | async function (async) |   |  
-- | -- | -- | --
  | init | @ | gobridge.js:15
  | default_1 | @ | gobridge.js:20
  | ./src/main.go | @ | main.go:2
  | __webpack_require__ | @ | bootstrap:19
  | ./src/App.svelte | @ | log.js:59
  | __webpack_require__ | @ | bootstrap:19
  | ./src/main.js | @ | main.js:1
  | __webpack_require__ | @ | bootstrap:19
  | 1 | @ | GoGitClonePanel.svelte:78
  | __webpack_require__ | @ | bootstrap:19
  | (anonymous) | @ | bootstrap:83
  | (anonymous) | @ | bootstrap:83
```

**Comment by happybeing** [comment]
Was that after a clean clone?

**Comment by tylerchilds** [comment]
@happybeing yes, blew away the existing folder and started from scratch

**Comment by happybeing** [comment]
Thanks Tyler, so far we have you and one other with this issue (but slightly different messages) and two without (plus me). Please can you post the information I've now requested [here](https://github.com/happybeing/p2p-git-portal-poc/issues/5#issuecomment-731635038). I can't replicate this myself yet but have some ideas and will look at the errors we're getting and see where this leads. It looks like a difference between host systems, but from what I have so far I don't know what.

**Comment by happybeing** [comment]
@tylerchilds assuming you are NOT using Go v.1.13, you could try the following.

starting in the p2p-git-portal-directory
edit ./node_modules/golang-wasm-async-loader2/dist/index.js

Replace:
`path_1.join(__dirname, "..", "lib", "wasm_exec.js"),`
with
`path_1.join(process.env.GOROOT, "/misc/wasm/wasm_exec.js"),`

Let me know what happens if you try this. There's a chance it will work!

**Comment by tylerchilds** [comment]
We're live! Was able to clone the test repo :)

I was on 1.15, so that was the issue! I tried replacing the path_1 line first, and that got past our first issue and hit a second one. I decided to stop going down this rabbit trial.

So then I jumped to 1.13.15, blew away the repo again and with a fresh pull, seems like it's all working for me.

Thanks for helping me get the environment setup :)

**Comment by happybeing** [comment]
Great :smile: Thanks for testing this out. Can you recall the console error with v1.15 just to confirm it is what I saw before? What I had before is as follows, but they've made changes which I was hoping would eliminate this:

`   Uncaught (in promise) TypeError: fs.writeSync is not a function`

Then I'll think about how best to support different Go versions with the plugin.

**Comment by happybeing** [comment]
SUMMARY: this issue was caused by using a different version of the Go compiler from the one supported by the `golang-wasm-async-loader2@1.0.6` dependency which is designed to work with Go v1.13.

SOLUTION: for now, you must use Go v1.13.

Later, the `golang-wasm-async-loader2` needs modifying but as this will be made easier when Go wasm has fixed the underlying issue, I plan to leave this until the v1.16 release of Go. This is recorded in the plugin issue: https://github.com/happybeing/webpack-golang-wasm-async-loader/issues/1
